### ISSUE TITLE
DTMF Command *AA11310997D Sends as Talk Group Instead of Private Call on DMR BrandMeister

### ISSUE THREAD

**Issue by porpup** [BillJr99/digital_link#1]
Hello Sir,
First of all, thank you very much for your tremendous work on this project. It has truly made it much easier for us to use DTMF commands with our AllStar nodes.
I’m currently facing an issue when trying to initiate a Parrot Private Call on DMR BrandMeister using the following DTMF command:

*AA11310997D

Unfortunately, this command results in a Talk Group call rather than a Private Call as expected.
Could you please advise if there’s a specific format or configuration needed to make a Private Call work correctly? I’d appreciate any guidance or suggestions.

Best regards,
VE2ORU

**Comment by BillJr99** [comment]
Thank you Oleksandr!

It looks like I made a typo in the README -- I convert asterisks to pound
symbols (other than the leading one to open the DTMF parser), and I believe
the # symbol is the dvswitch private call flag.

I haven't had a chance to verify this, but if my intuition is correct, then
this should work:

*AA11310997*

Keep me posted and I'll be glad to take a closer look.

Thanks again for catching this!

Bill W1CLK

**Comment by porpup** [comment]
Unfortunately * at the end also not working. I tested *AA11310997 * and *AA119990 * didn't work as Private Call Parrot call (it behaves as Talk Group and don't send you back recordings of your voice). But *AA114000 * works great and disconnects from Talk Group in use. I found another problem: *AA0 doesn't work as disconnect from TG (Talk Group)

**Comment by BillJr99** [comment]
Hm, this is odd.  I have the extensions.conf set up to convert the D to a #
for this purpose too.  I'll add a separate check for that in my script, but
I wonder what else is going on here, especially since *AA0 doesn't unlink.
Sorry about that!

There is a log file generated at /opt/digital_link/dvswitch_links.log --
would you be willing to send that to me (my call sign @ arrl.net)?  I'll
take a look and see what's happening there.

Bill W1CLK

**Comment by porpup** [comment]
with only this:

/etc/asterisk/extensions.conf

Modify extensions.conf by adding the following stanza (again, replace _A. with _@., where @ is the DTMF tone you used in rpt.conf above):

[digital_link]
exten => _A.,n(normal),System(/opt/digital_link/digital_link.sh ${EXTEN})
exten => _A.,n,Hangup

I am not able connect with DTMF command at all so I still use:

[digital_link]
; Match extensions explicitly ending with D
exten => _A.,1,GotoIf($["${EXTEN:-1}"="D"]?ends_with_D:normal)
; If it ends with D, replace the last character with #
exten => _A.,n(ends_with_D),System(/opt/digital_link/digital_link.sh ${EXTEN:0:-1}#)
exten => _A.,n,Hangup
; If it does not end with D, process normally
exten => _A.,n(normal),System(/opt/digital_link/digital_link.sh ${EXTEN})
exten => _A.,n,Hangup

**Comment by porpup** [comment]
*AA0 command works great! *AA11310997D and *AA119990D still don't work, but I can live without those not important Private Calls Parrot tests.

Thank you so much for your hard work.

73

**Comment by BillJr99** [comment]
Ah ok great!  Well that's one step in the right direction.  Would you mind
sending me your log one more time and I'll check out what's going on with
those private calls?  I'd love to fix that.

Bill

**Comment by porpup** [comment]
Wed 28 May 15:01:08 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:01:10 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=91
Wed 28 May 15:02:27 EDT 2025: Executing with A0
Wed 28 May 15:02:27 EDT 2025: Invalid DTMF command 0
Wed 28 May 15:04:05 EDT 2025: Executing with A114000
Wed 28 May 15:04:06 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:04:08 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=4000
Wed 28 May 15:18:38 EDT 2025: Executing with A113109
Wed 28 May 15:18:41 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:18:43 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=3109
Wed 28 May 15:19:44 EDT 2025: Executing with A11310997D
Wed 28 May 15:19:45 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:19:47 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997#
Wed 28 May 15:20:39 EDT 2025: Executing with A0
Wed 28 May 15:20:40 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:20:40 EDT 2025: Unlinked from current node
Wed 28 May 15:21:15 EDT 2025: Executing with A119990D
Wed 28 May 15:21:15 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:21:17 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=9990#
Wed 28 May 15:21:44 EDT 2025: Executing with A32
Wed 28 May 15:21:44 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:21:46 EDT 2025: Connected to node 65138, Mode=YSF, Master=2, TG=
Wed 28 May 15:26:39 EDT 2025: Executing with A32
Wed 28 May 15:26:39 EDT 2025: Unlinked on mode YSFN
Wed 28 May 15:26:42 EDT 2025: Connected to node 65138, Mode=YSF, Master=2, TG=
Wed 28 May 15:27:16 EDT 2025: Executing with A0
Wed 28 May 15:27:16 EDT 2025: Unlinked on mode YSFN
Wed 28 May 15:27:16 EDT 2025: Unlinked from current node
Wed 28 May 15:28:24 EDT 2025: Executing with A11310997D
Wed 28 May 15:28:25 EDT 2025: Unlinked on mode YSFN
Wed 28 May 15:28:27 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997#
Wed 28 May 15:29:42 EDT 2025: Executing with A0
Wed 28 May 15:29:43 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:29:43 EDT 2025: Unlinked from current node
Wed 28 May 15:33:46 EDT 2025: Executing with A00
Wed 28 May 15:33:46 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:33:46 EDT 2025: Disconnected node 65138
Wed 28 May 15:47:42 EDT 2025: Executing with A11310997D
Wed 28 May 15:47:44 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:47:47 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997#
Wed 28 May 15:50:33 EDT 2025: Executing with A119990D
Wed 28 May 15:50:34 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:50:36 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=9990#
Wed 28 May 15:50:57 EDT 2025: Executing with A0
Wed 28 May 15:50:57 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:50:57 EDT 2025: Unlinked from current node
Wed 28 May 15:51:20 EDT 2025: Executing with A32
Wed 28 May 15:51:21 EDT 2025: Unlinked on mode DMR
Wed 28 May 15:51:23 EDT 2025: Connected to node 65138, Mode=YSF, Master=2, TG=
Wed 28 May 15:52:14 EDT 2025: Executing with A32
Wed 28 May 15:52:14 EDT 2025: Unlinked on mode YSFN
Wed 28 May 15:52:16 EDT 2025: Connected to node 65138, Mode=YSF, Master=2, TG=
Wed 28 May 15:52:52 EDT 2025: Executing with A0
Wed 28 May 15:52:53 EDT 2025: Unlinked on mode YSFN
Wed 28 May 15:52:53 EDT 2025: Unlinked from current node
Wed 28 May 15:53:20 EDT 2025: Executing with A1191
Wed 28 May 15:53:20 EDT 2025: Unlinked on mode YSFN
Wed 28 May 15:53:22 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=91

On May 28, 2025, at 15:48, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917439476>
Ah ok great! Well that's one step in the right direction. Would you mind
sending me your log one more time and I'll check out what's going on with
those private calls? I'd love to fix that.

Bill

**Comment by BillJr99** [comment]
Thanks a lot for that.  This is odd - it is linking to TG 310997# when you enter 310997D.  Usually that creates a private call.  I wonder if our versions of dvswitch.sh are different?  I'll look into this more, but I'll close this issue for now since it's sending the right TG.

**Comment by porpup** [comment]
It seems like DVSwitch issue to me too

28 мая 2025 г., в 16:00, William Mongan ***@***.***> написал(а):

﻿
[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917467348>

Thanks a lot for that. This is odd - it is linking to TG 310997# when you enter 310997D. Usually that creates a private call. I wonder if our versions of dvswitch.sh are different? I'll look into this more, but I'll close this issue for now since it's sending the right TG.

**Comment by BillJr99** [comment]
I wonder if I need to escape the # symbol in the tune command -- I just pushed a change that does this, if you'd like to try it!

**Comment by porpup** [comment]
P.S. I was using “Ham Crusader” video guides for DVSwitch installation. Also I am using latest version of DVSwitch which came with updates

28 мая 2025 г., в 16:00, William Mongan ***@***.***> написал(а):

﻿
[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917467348>

Thanks a lot for that. This is odd - it is linking to TG 310997# when you enter 310997D. Usually that creates a private call. I wonder if our versions of dvswitch.sh are different? I'll look into this more, but I'll close this issue for now since it's sending the right TG.

**Comment by porpup** [comment]
﻿
P.S. I was using “Ham Crusader” video guides for DVSwitch installation. Also I am using latest version of DVSwitch which came with updates

28 мая 2025 г., в 16:00, William Mongan ***@***.***> написал(а):

﻿
[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917467348>

Thanks a lot for that. This is odd - it is linking to TG 310997# when you enter 310997D. Usually that creates a private call. I wonder if our versions of dvswitch.sh are different? I'll look into this more, but I'll close this issue for now since it's sending the right TG.

**Comment by porpup** [comment]
Still not working if I use terminal command:
sudo /opt/MMDVM_Bridge/dvswitch.sh tune 310997#
Than it works

On May 28, 2025, at 16:06, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917479450>

I wonder if I need to escape the # symbol in the tune command -- I just pushed a change that does this, if you'd like to try it!

**Comment by BillJr99** [comment]
Ah good idea, thanks!  OK, I've added some logs and increased my quoting of environment variables that could have a # in them.  If you're willing, feel free to pull that and give it a try, and send me the log which will have some more info in it for me to work with.  Thanks again for this!

**Comment by porpup** [comment]
Still nothing…

Wed 28 May 17:32:30 EDT 2025: Executing with A11310997D
Connecting node 65138 to 1000...
Wed 28 May 17:32:32 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#
Wed 28 May 17:32:35 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997#
Wed 28 May 17:33:55 EDT 2025: Executing with A11310997D
Wed 28 May 17:33:56 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#
Wed 28 May 17:33:58 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997#
Wed 28 May 17:34:48 EDT 2025: Executing with A0
Wed 28 May 17:34:48 EDT 2025: Unlinked on mode DMR
Wed 28 May 17:34:48 EDT 2025: Unlinked from current node
Wed 28 May 17:35:20 EDT 2025: Executing with A11310997D
Wed 28 May 17:35:20 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#
Wed 28 Ma

On May 28, 2025, at 16:50, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917579910>

Ah good idea, thanks! OK, I've added some logs and increased my quoting of environment variables that could have a # in them. If you're willing, feel free to pull that and give it a try, and send me the log which will have some more info in it for me to work with. Thanks again for this!

**Comment by BillJr99** [comment]
Thanks so much again!  If you copy and paste these into your terminal, do they work (with your ***'s replaced with your actual data - thanks for scrubbing that)?

/opt/MMDVM_Bridge/dvswitch.sh mode DMR
/opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#

**Comment by porpup** [comment]
I attached image to this email.
If you can see closely when I use in terminal this line:

sudo /opt/MMDVM_Bridge/dvswitch.sh tune 310997#

It connects to DMR TS2 and with your script only to DMR.

[Screen Shot 2025-05-28 at 17.43.39 PM.png]

On May 28, 2025, at 16:50, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917579910>

Ah good idea, thanks! OK, I've added some logs and increased my quoting of environment variables that could have a # in them. If you're willing, feel free to pull that and give it a try, and send me the log which will have some more info in it for me to work with. Thanks again for this!

**Comment by BillJr99** [comment]
Would you mind emailing that screenshot directly to me?  I don't think it attached here, sorry about that!

**Comment by porpup** [comment]
***@***.***:~ $ sudo /opt/MMDVM_Bridge/dvswitch.sh mode DMR
***@***.***:~ $ sudo /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#
bash: !310997: event not found
***@***.***:~ $

On May 28, 2025, at 17:43, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917685533>

Thanks so much again! If you copy and paste these into your terminal, do they work (with your ***'s replaced with your actual data - thanks for scrubbing that)?

/opt/MMDVM_Bridge/dvswitch.sh mode DMR
/opt/MMDVM_Bridge/dvswitch.sh tune @.***:62031!310997#

**Comment by BillJr99** [comment]
Ah! OK - it's not the pound sign, but the exclamation point in the command.  Bash is interpreting that as the history expansion operator even when I quote it in the script.  I'm going to try disabling history expansion within the script with set +H -- I just checked that in.  This is really helpful, thank you for this!

**Comment by porpup** [comment]
After your recent modification still not working:

Wed 28 May 17:42:22 EDT 2025: Executing with A11310997
Wed 28 May 17:42:23 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997
Wed 28 May 17:42:25 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997
Wed 28 May 17:42:54 EDT 2025: Executing with A11310997D
Wed 28 May 17:42:54 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#
Wed 28 May 17:42:56 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997#
Wed 28 May 17:58:48 EDT 2025: Executing with A11310997D
Connecting node 65138 to 1000...
Wed 28 May 17:58:51 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#
Wed 28 May 17:58:53 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997#
Wed 28 May 17:59:39 EDT 2025: Executing with A11310997D
Wed 28 May 17:59:39 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#
Wed 28 May 17:59:41 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997#


On May 28, 2025, at 17:54, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917702971>

Ah! OK - it's not the pound sign, but the exclamation point in the command. Bash is interpreting that as the history expansion operator even when I quote it in the script. I'm going to try disabling history expansion within the script with set +H -- I just checked that in. This is really helpful, thank you for this!

**Comment by porpup** [comment]
***@***.***:~ $ sudo /opt/MMDVM_Bridge/dvswitch.sh mode DMR
***@***.***:~ $ sudo nano /opt/digital_link/dvswitch_links.log
***@***.***:~ $ sudo ^[[200~/opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997
bash: !310997: event not found
***@***.***:~ $ sudo /opt/MMDVM_Bridge/dvswitch.sh tune ***@***.***:62031!310997#
bash: !310997: event not found
***@***.***:~ $

On May 28, 2025, at 17:54, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917702971>

Ah! OK - it's not the pound sign, but the exclamation point in the command. Bash is interpreting that as the history expansion operator even when I quote it in the script. I'm going to try disabling history expansion within the script with set +H -- I just checked that in. This is really helpful, thank you for this!

**Comment by porpup** [comment]
I fixed your script for you and it works!!!!:

#!/bin/bash
# Run as asterisk or root

set +H  # Disable Bash history expansion (! operator)

# Node configuration
NODE_ID=62933
LINKED_NODE_ID=1999
CONFIG_FILE="/opt/digital_link/switch_modes.conf"
LOG_FILE="/opt/digital_link/dvswitch_links.log"
DVSWITCH_APP="/opt/MMDVM_Bridge/dvswitch.sh"

echo "$(date): Executing with $1" >> $LOG_FILE

# Input DTMF string
DTMF=$1
DTMF=${DTMF:1}
DTMF=${DTMF//\*/\#}

if [[ -z "$DTMF" ]]; then
    echo "Invalid DTMF command. Exiting."
    echo "$(date): Invalid DTMF command ${DTMF}" >> $LOG_FILE
    exit 1
fi

MODE_DIGIT=${DTMF:0:1}
MASTER=${DTMF:1:1}
TG=${DTMF:2}

unlink_current_mode() {
    DMR_UNLINK=4000
    DSTAR_UNLINK=U
    YSF_UNLINK=4000
    NXDN_UNLINK=9999
    P25_UNLINK=9999

    local current_mode=$(${DVSWITCH_APP} mode)

    case $current_mode in
        DMR) ${DVSWITCH_APP} tune ${DMR_UNLINK} ;;
        DSTAR) ${DVSWITCH_APP} tune ${DSTAR_UNLINK} ;;
        YSF|YSFN) ${DVSWITCH_APP} tune ${YSF_UNLINK} ;;
        NXDN) ${DVSWITCH_APP} tune ${NXDN_UNLINK} ;;
        P25) ${DVSWITCH_APP} tune ${P25_UNLINK} ;;
        *)
            echo "WARNING: Unable to unlink unsupported mode: $current_mode"
            echo "WARNING: Unable to unlink unsupported mode: $current_mode" >> $LOG_FILE
            ;;
    esac
    echo Unlinked on mode $current_mode
    echo "$(date): Unlinked on mode $current_mode" >> $LOG_FILE
}

if [[ "$MODE_DIGIT" == "0" && "$MASTER" == "0" ]]; then
    echo "Disconnecting node $NODE_ID from AllStarLink..."
    echo "Disconnecting node $NODE_ID from AllStarLink..." >> $LOG_FILE
    unlink_current_mode
    asterisk -rx "rpt cmd $NODE_ID ilink 1 ${LINKED_NODE_ID}"
    echo "Node $NODE_ID disconnected from AllStarLink."
    echo "$(date): Disconnected node $NODE_ID" >> $LOG_FILE
    exit 0
fi

if [[ "$MODE_DIGIT" == "0" ]]; then
    echo "Unlinking only"
    unlink_current_mode
    echo "Node $NODE_ID unlinked."
    echo "$(date): Unlinked from current node" >> $LOG_FILE
    exit 0
fi

CURRENT_CONNECTION=$(asterisk -rx "rpt lstats $NODE_ID" | grep "ESTABLISHED")
if [[ -n "$CURRENT_CONNECTION" && "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Disconnecting from other nodes..."
    echo "Disconnecting from other nodes..." >> $LOG_FILE
    asterisk -rx "rpt cmd $NODE_ID ilink 6 1"
fi
if [[ "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..."
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..." >> $LOG_FILE
    asterisk -rx "rpt fun $NODE_ID *3$LINKED_NODE_ID"
    sleep 2
fi

SECTION=$(awk -v modemaster="${MODE_DIGIT}${MASTER}" '
    /^\[.*\]/ { section=$0; in_section=0 }
    $0 ~ "modemaster="modemaster { in_section=1 }
    in_section { print section; exit }
' "$CONFIG_FILE")

if [[ -z "$SECTION" ]]; then
    echo "No matching configuration for MASTER=${MASTER}. Exiting."
    echo "No matching configuration for MASTER=${MASTER}. Exiting." >> $LOG_FILE
    exit 1
fi

MODE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^mode=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

URL=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^url=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PORT=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^port=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PASSWORD=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^password=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

TYPE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^type=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

unlink_current_mode

echo "Switching to mode $MODE, MASTER=${MASTER}, TG: $TG, URL: $URL, PORT: $PORT, PASSWORD: $PASSWORD, TYPE: $TYPE"

if [[ "$MODE" == "D-STAR" ]]; then
    if [[ "${TG: -1}" == "D" ]]; then
        TG="${TG%#}E"
    fi
    TG="${TYPE}${TG}L"
fi

# ✅ Handle DMR Private Call correctly
if [[ "$MODE" == "DMR" && "${TG: -1}" == "D" ]]; then
    TG="${TG%?}#"  # Convert D suffix to #
    ${DVSWITCH_APP} mode DMR
    echo Executing: ${DVSWITCH_APP} mode DMR
    echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE
    ${DVSWITCH_APP} tune "${TG}"
    echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
    echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG (Private Call)" >> $LOG_FILE
    exit 0
fi

case $MODE in
    DMR)
        ${DVSWITCH_APP} mode DMR
        echo Executing: ${DVSWITCH_APP} mode DMR
        echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE
        ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}!${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}!${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}!${TG}" >> $LOG_FILE
        ;;
    D-STAR)
        ${DVSWITCH_APP} mode DSTAR
        echo Executing: ${DVSWITCH_APP} mode DSTAR >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    YSF)
        ${DVSWITCH_APP} mode YSF
        echo Executing: ${DVSWITCH_APP} mode YSF >> $LOG_FILE
        ${DVSWITCH_APP} tune "${URL}:${PORT}"
        echo Executing: ${DVSWITCH_APP} tune "${URL}:${PORT}" >> $LOG_FILE
        ;;
    NXDN)
        ${DVSWITCH_APP} mode NXDN
        echo Executing: ${DVSWITCH_APP} mode NXDN >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    P25)
        ${DVSWITCH_APP} mode P25
        echo Executing: ${DVSWITCH_APP} mode P25 >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    *)
        echo "Unsupported mode: $MODE"
        echo "Unsupported mode: $MODE" >> $LOG_FILE
        exit 1
        ;;
esac

echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG" >> $LOG_FILE


On May 28, 2025, at 17:54, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917702971>

Ah! OK - it's not the pound sign, but the exclamation point in the command. Bash is interpreting that as the history expansion operator even when I quote it in the script. I'm going to try disabling history expansion within the script with set +H -- I just checked that in. This is really helpful, thank you for this!

**Comment by porpup** [comment]
Log for working code:

Wed 28 May 18:13:55 EDT 2025: Executing with A11310997D
Connecting node 65138 to 1000...
Wed 28 May 18:13:57 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune 310997#
Wed 28 May 18:14:00 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997# (Private Call)
Wed 28 May 18:16:29 EDT 2025: Executing with A119990D
Wed 28 May 18:16:29 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune 9990#
Wed 28 May 18:16:31 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=9990# (Private Call)
Wed 28 May 18:17:12 EDT 2025: Executing with A11310997D
Wed 28 May 18:17:13 EDT 2025: Unlinked on mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh mode DMR
Executing: /opt/MMDVM_Bridge/dvswitch.sh tune 310997#
Wed 28 May 18:17:15 EDT 2025: Connected to node 65138, Mode=DMR, Master=1, TG=310997# (Private Call)


On May 28, 2025, at 18:15, Oleksandr Shyryayev ***@***.***> wrote:

I fixed your script for you and it works!!!!:

#!/bin/bash
# Run as asterisk or root

set +H  # Disable Bash history expansion (! operator)

# Node configuration
NODE_ID=62933
LINKED_NODE_ID=1999
CONFIG_FILE="/opt/digital_link/switch_modes.conf"
LOG_FILE="/opt/digital_link/dvswitch_links.log"
DVSWITCH_APP="/opt/MMDVM_Bridge/dvswitch.sh"

echo "$(date): Executing with $1" >> $LOG_FILE

# Input DTMF string
DTMF=$1
DTMF=${DTMF:1}
DTMF=${DTMF//\*/\#}

if [[ -z "$DTMF" ]]; then
    echo "Invalid DTMF command. Exiting."
    echo "$(date): Invalid DTMF command ${DTMF}" >> $LOG_FILE
    exit 1
fi

MODE_DIGIT=${DTMF:0:1}
MASTER=${DTMF:1:1}
TG=${DTMF:2}

unlink_current_mode() {
    DMR_UNLINK=4000
    DSTAR_UNLINK=U
    YSF_UNLINK=4000
    NXDN_UNLINK=9999
    P25_UNLINK=9999

    local current_mode=$(${DVSWITCH_APP} mode)

    case $current_mode in
        DMR) ${DVSWITCH_APP} tune ${DMR_UNLINK} ;;
        DSTAR) ${DVSWITCH_APP} tune ${DSTAR_UNLINK} ;;
        YSF|YSFN) ${DVSWITCH_APP} tune ${YSF_UNLINK} ;;
        NXDN) ${DVSWITCH_APP} tune ${NXDN_UNLINK} ;;
        P25) ${DVSWITCH_APP} tune ${P25_UNLINK} ;;
        *)
            echo "WARNING: Unable to unlink unsupported mode: $current_mode"
            echo "WARNING: Unable to unlink unsupported mode: $current_mode" >> $LOG_FILE
            ;;
    esac
    echo Unlinked on mode $current_mode
    echo "$(date): Unlinked on mode $current_mode" >> $LOG_FILE
}

if [[ "$MODE_DIGIT" == "0" && "$MASTER" == "0" ]]; then
    echo "Disconnecting node $NODE_ID from AllStarLink..."
    echo "Disconnecting node $NODE_ID from AllStarLink..." >> $LOG_FILE
    unlink_current_mode
    asterisk -rx "rpt cmd $NODE_ID ilink 1 ${LINKED_NODE_ID}"
    echo "Node $NODE_ID disconnected from AllStarLink."
    echo "$(date): Disconnected node $NODE_ID" >> $LOG_FILE
    exit 0
fi

if [[ "$MODE_DIGIT" == "0" ]]; then
    echo "Unlinking only"
    unlink_current_mode
    echo "Node $NODE_ID unlinked."
    echo "$(date): Unlinked from current node" >> $LOG_FILE
    exit 0
fi

CURRENT_CONNECTION=$(asterisk -rx "rpt lstats $NODE_ID" | grep "ESTABLISHED")
if [[ -n "$CURRENT_CONNECTION" && "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Disconnecting from other nodes..."
    echo "Disconnecting from other nodes..." >> $LOG_FILE
    asterisk -rx "rpt cmd $NODE_ID ilink 6 1"
fi
if [[ "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..."
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..." >> $LOG_FILE
    asterisk -rx "rpt fun $NODE_ID *3$LINKED_NODE_ID"
    sleep 2
fi

SECTION=$(awk -v modemaster="${MODE_DIGIT}${MASTER}" '
    /^\[.*\]/ { section=$0; in_section=0 }
    $0 ~ "modemaster="modemaster { in_section=1 }
    in_section { print section; exit }
' "$CONFIG_FILE")

if [[ -z "$SECTION" ]]; then
    echo "No matching configuration for MASTER=${MASTER}. Exiting."
    echo "No matching configuration for MASTER=${MASTER}. Exiting." >> $LOG_FILE
    exit 1
fi

MODE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^mode=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

URL=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^url=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PORT=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^port=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PASSWORD=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^password=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

TYPE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^type=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

unlink_current_mode

echo "Switching to mode $MODE, MASTER=${MASTER}, TG: $TG, URL: $URL, PORT: $PORT, PASSWORD: $PASSWORD, TYPE: $TYPE"

if [[ "$MODE" == "D-STAR" ]]; then
    if [[ "${TG: -1}" == "D" ]]; then
        TG="${TG%#}E"
    fi
    TG="${TYPE}${TG}L"
fi

# ✅ Handle DMR Private Call correctly
if [[ "$MODE" == "DMR" && "${TG: -1}" == "D" ]]; then
    TG="${TG%?}#"  # Convert D suffix to #
    ${DVSWITCH_APP} mode DMR
    echo Executing: ${DVSWITCH_APP} mode DMR
    echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE
    ${DVSWITCH_APP} tune "${TG}"
    echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
    echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG (Private Call)" >> $LOG_FILE
    exit 0
fi

case $MODE in
    DMR)
        ${DVSWITCH_APP} mode DMR
        echo Executing: ${DVSWITCH_APP} mode DMR
        echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE
        ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}!${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}!${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}!${TG}" >> $LOG_FILE
        ;;
    D-STAR)
        ${DVSWITCH_APP} mode DSTAR
        echo Executing: ${DVSWITCH_APP} mode DSTAR >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    YSF)
        ${DVSWITCH_APP} mode YSF
        echo Executing: ${DVSWITCH_APP} mode YSF >> $LOG_FILE
        ${DVSWITCH_APP} tune "${URL}:${PORT}"
        echo Executing: ${DVSWITCH_APP} tune "${URL}:${PORT}" >> $LOG_FILE
        ;;
    NXDN)
        ${DVSWITCH_APP} mode NXDN
        echo Executing: ${DVSWITCH_APP} mode NXDN >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    P25)
        ${DVSWITCH_APP} mode P25
        echo Executing: ${DVSWITCH_APP} mode P25 >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    *)
        echo "Unsupported mode: $MODE"
        echo "Unsupported mode: $MODE" >> $LOG_FILE
        exit 1
        ;;
esac

echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG" >> $LOG_FILE


On May 28, 2025, at 17:54, William Mongan ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/1581249?s=20&v=4]BillJr99 left a comment (BillJr99/digital_link#1)<https://github.com/BillJr99/digital_link/issues/1#issuecomment-2917702971>

Ah! OK - it's not the pound sign, but the exclamation point in the command. Bash is interpreting that as the history expansion operator even when I quote it in the script. I'm going to try disabling history expansion within the script with set +H -- I just checked that in. This is really helpful, thank you for this!

**Comment by BillJr99** [comment]
oh ok!  looks like you are directly tuning the TG only - that might assume that you're already on a particular DMR server, and in that case you wouldn't need the host/port or the weird characters like the ! 

I wonder if it is possible to run multiple tune commands to link to the right host and then the TG - for example:

${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}"
${DVSWITCH_APP} tune "${TG}"

In the event that there is more than one DMR host url configured.

**Comment by porpup** [comment]
#!/bin/bash
# Run as asterisk or root

set +H  # Disable Bash history expansion (! operator)

# Node configuration
NODE_ID=62933
LINKED_NODE_ID=1999
CONFIG_FILE="/opt/digital_link/switch_modes.conf"
LOG_FILE="/opt/digital_link/dvswitch_links.log"
DVSWITCH_APP="/opt/MMDVM_Bridge/dvswitch.sh"

echo "$(date): Executing with $1" >> $LOG_FILE

# Input DTMF string
DTMF=$1
DTMF=${DTMF:1}
DTMF=${DTMF//\*/\#}

if [[ -z "$DTMF" ]]; then
    echo "Invalid DTMF command. Exiting."
    echo "$(date): Invalid DTMF command ${DTMF}" >> $LOG_FILE
    exit 1
fi

MODE_DIGIT=${DTMF:0:1}
MASTER=${DTMF:1:1}
TG=${DTMF:2}

unlink_current_mode() {
    DMR_UNLINK=4000
    DSTAR_UNLINK=U
    YSF_UNLINK=4000
    NXDN_UNLINK=9999
    P25_UNLINK=9999

    local current_mode=$(${DVSWITCH_APP} mode)

    case $current_mode in
        DMR) ${DVSWITCH_APP} tune ${DMR_UNLINK} ;;
        DSTAR) ${DVSWITCH_APP} tune ${DSTAR_UNLINK} ;;
        YSF|YSFN) ${DVSWITCH_APP} tune ${YSF_UNLINK} ;;
        NXDN) ${DVSWITCH_APP} tune ${NXDN_UNLINK} ;;
        P25) ${DVSWITCH_APP} tune ${P25_UNLINK} ;;
        *)
            echo "WARNING: Unable to unlink unsupported mode: $current_mode"
            echo "WARNING: Unable to unlink unsupported mode: $current_mode" >> $LOG_FILE
            ;;
    esac
    echo Unlinked on mode $current_mode
    echo "$(date): Unlinked on mode $current_mode" >> $LOG_FILE
}

if [[ "$MODE_DIGIT" == "0" && "$MASTER" == "0" ]]; then
    echo "Disconnecting node $NODE_ID from AllStarLink..."
    echo "Disconnecting node $NODE_ID from AllStarLink..." >> $LOG_FILE
    unlink_current_mode
    asterisk -rx "rpt cmd $NODE_ID ilink 1 ${LINKED_NODE_ID}"
    echo "Node $NODE_ID disconnected from AllStarLink."
    echo "$(date): Disconnected node $NODE_ID" >> $LOG_FILE
    exit 0
fi

if [[ "$MODE_DIGIT" == "0" ]]; then
    echo "Unlinking only"
    unlink_current_mode
    echo "Node $NODE_ID unlinked."
    echo "$(date): Unlinked from current node" >> $LOG_FILE
    exit 0
fi

CURRENT_CONNECTION=$(asterisk -rx "rpt lstats $NODE_ID" | grep "ESTABLISHED")
if [[ -n "$CURRENT_CONNECTION" && "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Disconnecting from other nodes..."
    echo "Disconnecting from other nodes..." >> $LOG_FILE
    asterisk -rx "rpt cmd $NODE_ID ilink 6 1"
fi
if [[ "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..."
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..." >> $LOG_FILE
    asterisk -rx "rpt fun $NODE_ID *3$LINKED_NODE_ID"
    sleep 2
fi

SECTION=$(awk -v modemaster="${MODE_DIGIT}${MASTER}" '
    /^\[.*\]/ { section=$0; in_section=0 }
    $0 ~ "modemaster="modemaster { in_section=1 }
    in_section { print section; exit }
' "$CONFIG_FILE")

if [[ -z "$SECTION" ]]; then
    echo "No matching configuration for MASTER=${MASTER}. Exiting."
    echo "No matching configuration for MASTER=${MASTER}. Exiting." >> $LOG_FILE
    exit 1
fi

MODE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^mode=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

URL=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^url=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PORT=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^port=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PASSWORD=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^password=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

TYPE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^type=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

unlink_current_mode

echo "Switching to mode $MODE, MASTER=${MASTER}, TG: $TG, URL: $URL, PORT: $PORT, PASSWORD: $PASSWORD, TYPE: $TYPE"

# --- D-STAR TG formatting ---
if [[ "$MODE" == "D-STAR" ]]; then
    if [[ "${TG: -1}" == "D" ]]; then
        TG="${TG%#}E"
    fi
    TG="${TYPE}${TG}L"
fi

# --- DMR Private Call ---
if [[ "$MODE" == "DMR" && "${TG: -1}" == "D" ]]; then
    TG="${TG%?}#"  # Convert D to #
    ${DVSWITCH_APP} mode DMR
    echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE
    ${DVSWITCH_APP} tune "${TG}"
    echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
    echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG (Private Call)" >> $LOG_FILE
    exit 0
fi

# --- Main tuning section ---
case $MODE in
    DMR)
        ${DVSWITCH_APP} mode DMR
        echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE

        # Two-step DMR: connect to master, then TG
        ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}"
        echo Executing: ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}" >> $LOG_FILE
        sleep 1

        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    D-STAR)
        ${DVSWITCH_APP} mode DSTAR
        echo Executing: ${DVSWITCH_APP} mode DSTAR >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    YSF)
        ${DVSWITCH_APP} mode YSF
        echo Executing: ${DVSWITCH_APP} mode YSF >> $LOG_FILE
        ${DVSWITCH_APP} tune "${URL}:${PORT}"
        echo Executing: ${DVSWITCH_APP} tune "${URL}:${PORT}" >> $LOG_FILE
        ;;
    NXDN)
        ${DVSWITCH_APP} mode NXDN
        echo Executing: ${DVSWITCH_APP} mode NXDN >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    P25)
        ${DVSWITCH_APP} mode P25
        echo Executing: ${DVSWITCH_APP} mode P25 >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    *)
        echo "Unsupported mode: $MODE"
        echo "Unsupported mode: $MODE" >> $LOG_FILE
        exit 1
        ;;
esac

echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG" >> $LOG_FILE

28 мая 2025 г., в 18:32, William Mongan ***@***.***> написал(а):


I wonder if it is possible to run multiple tune commands to link to the right host and then the TG - for example:

${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}"
${DVSWITCH_APP} tune "${TG}"

In the event that there is more than one DMR host url configured.

**Comment by porpup** [comment]
I realize another interesting behavior of DVSwitch:
If you are on, let’s say DMR TG and decide to change mode to, let’s say, YSF.
You changed to YSF but Dmr TG is still in background connected. So how about to reset TG which you were on and than change the mode?

Tell me what do u think:

#!/bin/bash
# Run as asterisk or root

set +H  # Disable Bash history expansion (! operator)

# Node configuration
NODE_ID=62933
LINKED_NODE_ID=1999
CONFIG_FILE="/opt/digital_link/switch_modes.conf"
LOG_FILE="/opt/digital_link/dvswitch_links.log"
DVSWITCH_APP="/opt/MMDVM_Bridge/dvswitch.sh"

echo "$(date): Executing with $1" >> $LOG_FILE

# Input DTMF string
DTMF=$1
DTMF=${DTMF:1}
DTMF=${DTMF//\*/\#}

if [[ -z "$DTMF" ]]; then
    echo "Invalid DTMF command. Exiting."
    echo "$(date): Invalid DTMF command ${DTMF}" >> $LOG_FILE
    exit 1
fi

MODE_DIGIT=${DTMF:0:1}
MASTER=${DTMF:1:1}
TG=${DTMF:2}

unlink_and_reset_mode() {
    local current_mode=$(${DVSWITCH_APP} mode)
    echo "$(date): Unlinking and resetting mode $current_mode" >> $LOG_FILE

    case $current_mode in
        DMR)
            ${DVSWITCH_APP} tune 4000
            sleep 1
            ;;
        DSTAR)
            ${DVSWITCH_APP} tune U
            sleep 1
            ;;
        YSF|YSFN)
            ${DVSWITCH_APP} tune 4000
            sleep 1
            ;;
        NXDN|P25)
            ${DVSWITCH_APP} tune 9999
            sleep 1
            ;;
    esac

    ${DVSWITCH_APP} reset
    echo "$(date): Reset completed for $current_mode" >> $LOG_FILE
}

tune_with_retry() {
    local tune_cmd="$1"
    local try=1
    local success=0

    while [[ $try -le 2 ]]; do
        echo "Try $try: ${DVSWITCH_APP} tune $tune_cmd"
        ${DVSWITCH_APP} tune "$tune_cmd"
        echo "$(date): Attempt $try - tune $tune_cmd" >> $LOG_FILE

        sleep 2

        if tail -n 20 /var/log/dvswitch.log | grep -q "$tune_cmd"; then
            success=1
            break
        fi

        try=$((try + 1))
    done

    if [[ $success -eq 0 ]]; then
        echo "$(date): Tune command failed after 2 attempts: $tune_cmd" >> $LOG_FILE
    fi
}

# Disconnect and Unlink only when MODE and MASTER are both 0
if [[ "$MODE_DIGIT" == "0" && "$MASTER" == "0" ]]; then
    echo "Disconnecting node $NODE_ID from AllStarLink..."
    echo "Disconnecting node $NODE_ID from AllStarLink..." >> $LOG_FILE
    unlink_and_reset_mode
    asterisk -rx "rpt cmd $NODE_ID ilink 1 ${LINKED_NODE_ID}"
    echo "Node $NODE_ID disconnected from AllStarLink."
    echo "$(date): Disconnected node $NODE_ID" >> $LOG_FILE
    exit 0
fi

if [[ "$MODE_DIGIT" == "0" ]]; then
    echo "Unlinking only"
    unlink_and_reset_mode
    echo "Node $NODE_ID unlinked."
    echo "$(date): Unlinked from current node" >> $LOG_FILE
    exit 0
fi

CURRENT_CONNECTION=$(asterisk -rx "rpt lstats $NODE_ID" | grep "ESTABLISHED")
if [[ -n "$CURRENT_CONNECTION" && "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Disconnecting from other nodes..." >> $LOG_FILE
    asterisk -rx "rpt cmd $NODE_ID ilink 6 1"
fi
if [[ "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..." >> $LOG_FILE
    asterisk -rx "rpt fun $NODE_ID *3$LINKED_NODE_ID"
    sleep 2
fi

SECTION=$(awk -v modemaster="${MODE_DIGIT}${MASTER}" '
    /^\[.*\]/ { section=$0; in_section=0 }
    $0 ~ "modemaster="modemaster { in_section=1 }
    in_section { print section; exit }
' "$CONFIG_FILE")

if [[ -z "$SECTION" ]]; then
    echo "No matching configuration for MASTER=${MASTER}. Exiting." >> $LOG_FILE
    exit 1
fi

MODE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^mode=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

URL=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^url=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PORT=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^port=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PASSWORD=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^password=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

TYPE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^type=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

unlink_and_reset_mode

if [[ "$MODE" == "D-STAR" ]]; then
    if [[ "${TG: -1}" == "D" ]]; then
        TG="${TG%#}E"
    fi
    TG="${TYPE}${TG}L"
fi

if [[ "$MODE" == "DMR" && "${TG: -1}" == "D" ]]; then
    TG="${TG%?}#"
    ${DVSWITCH_APP} mode DMR
    echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE
    tune_with_retry "${TG}"
    echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG (Private Call)" >> $LOG_FILE
    exit 0
fi

case $MODE in
    DMR)
        ${DVSWITCH_APP} mode DMR
        echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE
        ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}"
        sleep 1
        tune_with_retry "${TG}"
        ;;
    D-STAR)
        ${DVSWITCH_APP} mode DSTAR
        echo Executing: ${DVSWITCH_APP} mode DSTAR >> $LOG_FILE
        tune_with_retry "${TG}"
        ;;
    YSF)
        ${DVSWITCH_APP} mode YSF
        echo Executing: ${DVSWITCH_APP} mode YSF >> $LOG_FILE
        tune_with_retry "${URL}:${PORT}"
        ;;
    NXDN)
        ${DVSWITCH_APP} mode NXDN
        echo Executing: ${DVSWITCH_APP} mode NXDN >> $LOG_FILE
        tune_with_retry "${TG}"
        ;;
    P25)
        ${DVSWITCH_APP} mode P25
        echo Executing: ${DVSWITCH_APP} mode P25 >> $LOG_FILE
        tune_with_retry "${TG}"
        ;;
    *)
        echo "Unsupported mode: $MODE" >> $LOG_FILE
        exit 1
        ;;
esac

echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG" >> $LOG_FILE

28 мая 2025 г., в 18:52, Oleksandr Shyryayev ***@***.***> написал(а):

﻿
#!/bin/bash
# Run as asterisk or root

set +H  # Disable Bash history expansion (! operator)

# Node configuration
NODE_ID=62933
LINKED_NODE_ID=1999
CONFIG_FILE="/opt/digital_link/switch_modes.conf"
LOG_FILE="/opt/digital_link/dvswitch_links.log"
DVSWITCH_APP="/opt/MMDVM_Bridge/dvswitch.sh"

echo "$(date): Executing with $1" >> $LOG_FILE

# Input DTMF string
DTMF=$1
DTMF=${DTMF:1}
DTMF=${DTMF//\*/\#}

if [[ -z "$DTMF" ]]; then
    echo "Invalid DTMF command. Exiting."
    echo "$(date): Invalid DTMF command ${DTMF}" >> $LOG_FILE
    exit 1
fi

MODE_DIGIT=${DTMF:0:1}
MASTER=${DTMF:1:1}
TG=${DTMF:2}

unlink_current_mode() {
    DMR_UNLINK=4000
    DSTAR_UNLINK=U
    YSF_UNLINK=4000
    NXDN_UNLINK=9999
    P25_UNLINK=9999

    local current_mode=$(${DVSWITCH_APP} mode)

    case $current_mode in
        DMR) ${DVSWITCH_APP} tune ${DMR_UNLINK} ;;
        DSTAR) ${DVSWITCH_APP} tune ${DSTAR_UNLINK} ;;
        YSF|YSFN) ${DVSWITCH_APP} tune ${YSF_UNLINK} ;;
        NXDN) ${DVSWITCH_APP} tune ${NXDN_UNLINK} ;;
        P25) ${DVSWITCH_APP} tune ${P25_UNLINK} ;;
        *)
            echo "WARNING: Unable to unlink unsupported mode: $current_mode"
            echo "WARNING: Unable to unlink unsupported mode: $current_mode" >> $LOG_FILE
            ;;
    esac
    echo Unlinked on mode $current_mode
    echo "$(date): Unlinked on mode $current_mode" >> $LOG_FILE
}

if [[ "$MODE_DIGIT" == "0" && "$MASTER" == "0" ]]; then
    echo "Disconnecting node $NODE_ID from AllStarLink..."
    echo "Disconnecting node $NODE_ID from AllStarLink..." >> $LOG_FILE
    unlink_current_mode
    asterisk -rx "rpt cmd $NODE_ID ilink 1 ${LINKED_NODE_ID}"
    echo "Node $NODE_ID disconnected from AllStarLink."
    echo "$(date): Disconnected node $NODE_ID" >> $LOG_FILE
    exit 0
fi

if [[ "$MODE_DIGIT" == "0" ]]; then
    echo "Unlinking only"
    unlink_current_mode
    echo "Node $NODE_ID unlinked."
    echo "$(date): Unlinked from current node" >> $LOG_FILE
    exit 0
fi

CURRENT_CONNECTION=$(asterisk -rx "rpt lstats $NODE_ID" | grep "ESTABLISHED")
if [[ -n "$CURRENT_CONNECTION" && "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Disconnecting from other nodes..."
    echo "Disconnecting from other nodes..." >> $LOG_FILE
    asterisk -rx "rpt cmd $NODE_ID ilink 6 1"
fi
if [[ "$CURRENT_CONNECTION" != *"$LINKED_NODE_ID"* ]]; then
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..."
    echo "Connecting node $NODE_ID to $LINKED_NODE_ID..." >> $LOG_FILE
    asterisk -rx "rpt fun $NODE_ID *3$LINKED_NODE_ID"
    sleep 2
fi

SECTION=$(awk -v modemaster="${MODE_DIGIT}${MASTER}" '
    /^\[.*\]/ { section=$0; in_section=0 }
    $0 ~ "modemaster="modemaster { in_section=1 }
    in_section { print section; exit }
' "$CONFIG_FILE")

if [[ -z "$SECTION" ]]; then
    echo "No matching configuration for MASTER=${MASTER}. Exiting."
    echo "No matching configuration for MASTER=${MASTER}. Exiting." >> $LOG_FILE
    exit 1
fi

MODE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^mode=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

URL=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^url=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PORT=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^port=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

PASSWORD=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^password=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

TYPE=$(awk -v section="$SECTION" '
    $0 == section { in_section=1; next }
    in_section && /^\[.*\]/ { exit }
    in_section && $1 ~ /^type=/ { split($0, a, "="); print a[2]; exit }
' "$CONFIG_FILE")

unlink_current_mode

echo "Switching to mode $MODE, MASTER=${MASTER}, TG: $TG, URL: $URL, PORT: $PORT, PASSWORD: $PASSWORD, TYPE: $TYPE"

# --- D-STAR TG formatting ---
if [[ "$MODE" == "D-STAR" ]]; then
    if [[ "${TG: -1}" == "D" ]]; then
        TG="${TG%#}E"
    fi
    TG="${TYPE}${TG}L"
fi

# --- DMR Private Call ---
if [[ "$MODE" == "DMR" && "${TG: -1}" == "D" ]]; then
    TG="${TG%?}#"  # Convert D to #
    ${DVSWITCH_APP} mode DMR
    echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE
    ${DVSWITCH_APP} tune "${TG}"
    echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
    echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG (Private Call)" >> $LOG_FILE
    exit 0
fi

# --- Main tuning section ---
case $MODE in
    DMR)
        ${DVSWITCH_APP} mode DMR
        echo Executing: ${DVSWITCH_APP} mode DMR >> $LOG_FILE

        # Two-step DMR: connect to master, then TG
        ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}"
        echo Executing: ${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}" >> $LOG_FILE
        sleep 1

        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    D-STAR)
        ${DVSWITCH_APP} mode DSTAR
        echo Executing: ${DVSWITCH_APP} mode DSTAR >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    YSF)
        ${DVSWITCH_APP} mode YSF
        echo Executing: ${DVSWITCH_APP} mode YSF >> $LOG_FILE
        ${DVSWITCH_APP} tune "${URL}:${PORT}"
        echo Executing: ${DVSWITCH_APP} tune "${URL}:${PORT}" >> $LOG_FILE
        ;;
    NXDN)
        ${DVSWITCH_APP} mode NXDN
        echo Executing: ${DVSWITCH_APP} mode NXDN >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    P25)
        ${DVSWITCH_APP} mode P25
        echo Executing: ${DVSWITCH_APP} mode P25 >> $LOG_FILE
        ${DVSWITCH_APP} tune "${TG}"
        echo Executing: ${DVSWITCH_APP} tune "${TG}" >> $LOG_FILE
        ;;
    *)
        echo "Unsupported mode: $MODE"
        echo "Unsupported mode: $MODE" >> $LOG_FILE
        exit 1
        ;;
esac

echo "$(date): Connected to node $NODE_ID, Mode=$MODE, Master=$MASTER, TG=$TG" >> $LOG_FILE

28 мая 2025 г., в 18:32, William Mongan ***@***.***> написал(а):


I wonder if it is possible to run multiple tune commands to link to the right host and then the TG - for example:

${DVSWITCH_APP} tune "${PASSWORD}@${URL}:${PORT}"
${DVSWITCH_APP} tune "${TG}"

In the event that there is more than one DMR host url configured.

**Comment by BillJr99** [comment]
Hm, you might have found another bug then - I thought I was doing that too!

**Comment by BillJr99** [comment]
You were absolutely right!  I've pushed those updates and private calls seem to work again.  Thanks for catching this!

**Comment by BillJr99** [comment]
I made one other edit while fixing this, in case you do a pull of these updates.  I moved the node number out of the shell script and into the config file.  So, if you pull, you'll want to add this section to switch_modes.conf:

[NodeInfo]
NODE_ID=12345
LINKED_NODE_ID=1999

replacing 12345 and 1999 with your allstar node number and your linked private node number.  

I also cleaned up some of the unlinking when switching between modes, and that seems more stable now, too.

Many thanks again!

**Comment by porpup** [comment]
Hi William,


I just wanted to let you know that I’ve tested your code—and it works flawlessly. You did it! It’s solid and fully functional. I think it’s officially time to take it out of alpha (or beta) status. 🎉


Also, I wanted to mention that I brought up your work during one of Freddie Mac’s (Ham Radio Crusader KD5FMU) YouTube streams. He had great things to say about you and your contributions. Maybe one day he’ll even put together a guide on how to use DTMF commands on DVSwitch based on your code—now that it’s fully working, the timing feels just right.


Awesome work, and congrats again!


Best,

Oleksandr, VE2ORU

**Comment by porpup** [comment]
﻿

Hi William,


I just wanted to let you know that I’ve tested your code—and it works flawlessly. You did it! It’s solid and fully functional. I think it’s officially time to take it out of alpha (or beta) status. 🎉


Also, I wanted to mention that I brought up your work during one of Freddie Mac’s (Ham Radio Crusader KD5FMU) YouTube streams. He had great things to say about you and your contributions. Maybe one day he’ll even put together a guide on how to use DTMF commands on DVSwitch based on your code—now that it’s fully working, the timing feels just right.


Awesome work, and congrats again!


Best,

Oleksandr, VE2ORU

**Comment by BillJr99** [comment]
Oh that's awesome!  He got me into AllStar in the first place, so I'm more than happy to share.  And thanks to you for finding the bug - and the fix!
